# Cálculo de suma ponderada Z e implementación de función de activación con múltiples instancias (vectores y matrices de numpy)

Objetivo: Mostrar los principios básicos de cálculo de la suma ponderada y función de activación considerando:
* Clasificación binaria.
* 4 instancias de entrenamiento con 3 variables independientes.
* Implementación con los tipos de datos de la librería numpy.

Definiciones:

X:
  Instancias con las tres variables independientes.
  Arreglo numpy con dimensiones (4, 3).
  [
    x1_1, x1_2, x1_3
    x2_1, x2_2, x2_3
    x3_1, x3_2, x3_3
    x4_1, x4_2, x4_3
  ]

Y: 
  Variables dependientes asociadas a las instancias.
  Arreglo numpy con dimensiones (4, 1).
  [ 
    y1
    y2
    y3
    y4
  ]

w:
  Pesos correspondientes a cada variable independiente.
  Nota: Se emplean los mismos pesos en todas las instancias.
  Arreglo numpy con dimensiones (1, 3).
  [
    w1, w2, w3
  ]

b:
  El bias del modelo.
  float de Python.

Z:
  Resultado de la suma ponderada.
  [
    z1
    z2
    z3
    z4
  ]
  
f:
  La función de activación.

Y_hat:
  Predicción del modelo, resultado de invocar f(Z).
  arreglo numpy con dimensiones (4, 1)

In [1]:
import numpy as np

In [2]:
X = np.array( [
  [1, 2, 3],
  [10, 20, 30],
  [4, 8, 12],
  [11, 21, 31]
])

In [3]:
X.shape

(4, 3)

In [4]:
n_vars = X.shape[1]
n_vars

3

In [5]:
n_instances = X.shape[0]
n_instances

4

In [6]:
Y = np.array([[1], [-1], [1], [-1]])

In [7]:
Y.shape

(4, 1)

In [8]:
Y


array([[ 1],
       [-1],
       [ 1],
       [-1]])

In [9]:
np.random.seed(123)
# Asignamos valores fijos para comparar resultados con los ejercicios previos
w = np.array([[0.08718667752263232, 0.4072417636703983, 0.10770023493843905]])
# Asignación de valores aleatorios con numpy
#w = np.random.rand(n_vars).reshape(-1, 1)
w


array([[0.08718668, 0.40724176, 0.10770023]])

In [10]:
w.shape

(1, 3)

In [11]:
import random
random.seed(123)
b = random.random()
# Asignamos valores fijos para comparar resultados con los ejercicios previos
b = 0.9011988779516946
b

0.9011988779516946

In [12]:
print(X)
print(w)
print(b)
print(Y)

[[ 1  2  3]
 [10 20 30]
 [ 4  8 12]
 [11 21 31]]
[[0.08718668 0.40724176 0.10770023]]
0.9011988779516946
[[ 1]
 [-1]
 [ 1]
 [-1]]


In [13]:
Z = b + np.dot(X, w.T)
Z

array([[ 2.12596979],
       [13.14890797],
       [ 5.80028252],
       [13.75103665]])

In [15]:
def f(Z):
    return np.sign(Z)

In [16]:
Y_hat = f(Z)
Y_hat

array([[1.],
       [1.],
       [1.],
       [1.]])