# NuPy (Numerical Python)
## Introducción
### ¿Qué es?
NumPy es el paquete fundamental para cómputo científico en Python. Es una librería que provee de un objeto tipo arreglo multidimensional y varios objetos derivados tales como arreglos enmascarados y matrices, así como rutinas para operaciones ágiles con arreglos, incluyendo matemáticas, lógicas, manipulación de formas, ordenamiento, selección, I/O, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación de valores aleatorios y más.

### Beneficios
* La estructura de datos ndarray es más eficiente para almacenar y manejar datos numéricos, en comparación con las estructuras de la distribución estándar de Python.
* Las librerías escritas en lenguajes de bajo nivel -tales como C- pueden operar con datos almacenados en el ndarray de Numpy sin tener que copiar datos.

## Estructura de datos (ndarray)
### Concepto
Arreglo multidimensional rápido y eficiente respecto al almacenamiento, el cual puede funcionar para almacenar datos homogéneos. Provee de operaciones aritméticas con soporte a vectorización.

### Crear ndarray

In [1]:
import numpy as np
#Crear un ndarray
r = range(10)
np.array(r)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Crer NdArray personalizados

In [2]:
#Arreglo de una dimensión con 10 elementos con valor 0.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Arreglo de dos dimensiones con 6 elementos con valor 1.
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
# Arreglo de dos dimensiones con valores aleatorios
randarray = np.random.randn(2,3)
randarray

array([[-0.89354492, -1.47190172,  0.76316343],
       [-0.05820717, -0.51414603, -1.10076855]])

In [5]:
#Arreglo de tres dimensiones con valores no inicializados
np.empty((3,4,5))
#La función empty no garantiza regresar valores cero

array([[[9.47563246e-312, 9.47557515e-312, 3.16202013e-322,
         1.79334108e-309, 8.48828113e-314],
        [2.71615461e-312, 0.00000000e+000, 6.54897132e-308,
         8.48798317e-314, 3.16202013e-322],
        [6.54302548e-308, 6.36726715e-314, 2.71615461e-312,
         0.00000000e+000,             nan],
        [8.48798316e-314, 3.16202013e-322,             nan,
         6.36598737e-314, 2.71615461e-312]],

       [[0.00000000e+000,             nan, 8.48798316e-314,
         3.16202013e-322,             nan],
        [6.36598737e-314, 1.35807731e-312, 0.00000000e+000,
                     nan, 8.48798316e-314],
        [3.16202013e-322,             nan, 6.36598737e-314,
         1.35807731e-312, 0.00000000e+000],
        [            nan, 8.48798316e-314, 3.16202013e-322,
                     nan, 6.36598737e-314]],

       [[1.35807731e-312, 0.00000000e+000,             nan,
         8.48798316e-314, 3.16202013e-322],
        [            nan, 6.36598737e-314, 1.35807731e-312,


In [6]:
# Versión de ndarray de la función range de Python
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
# Obtener el número de dimensiones
somearray = np.empty((3,4,5))
somearray.shape

(3, 4, 5)

In [8]:
# Obtener el tipo de datos
somearray.dtype

dtype('float64')

In [9]:
# Casting explícito
somearray2 = somearray.astype(np.int32)
somearray2.dtype
somearray2

C:\Users\Marciano\AppData\Local\Temp\ipykernel_17456\2496454525.py:2: RuntimeWarning: invalid value encountered in cast
  somearray2 = somearray.astype(np.int32)


array([[[          0,           0,           0,           0,
                   0],
        [          0, -2147483648,           0,           0,
                   0],
        [-2147483648,           0, -2147483648,           0,
                   0],
        [-2147483648,           0,           0,           0,
                   0]],

       [[          0, -2147483648,           0,           0,
                   0],
        [          0,           0,           0,           0,
                   0],
        [-2147483648, -2147483648,           0,           0,
                   0],
        [          0, -2147483648,           0,           0,
                   0]],

       [[          0,           0, -2147483648, -2147483648,
         -2147483648],
        [          0,           0, -2147483648,           0,
         -2147483648],
        [          0,           0, -2147483648,           0,
         -2147483648],
        [          0, -2147483648, -2147483648, -2147483648,
           

## Slicing (índices y subconjuntos)

* Slicing provee de una vista de los datos originales. No se copian los datos. Cualquier modificación a la vista se verá reflejada en los datos originales.
* Es posible llevar a cabo una copia de los datos por medio de la función copy.

In [10]:
#Copia explícita
somearray[2:6].copy

<function ndarray.copy>

In [11]:
#El indexado de arreglos multidimensionales puede tener dos formas
somearray[0][0][0]

9.475560124166e-312

In [12]:
somearray[0,0,0]

9.475560124166e-312

## Transposición
Una forma especial de cambio de forma que regresa una vsita de los datos, no copia.

In [13]:
transposeme = np.random.randn(3,4)
transposeme

array([[ 1.17018056, -0.23635896,  0.64757156,  0.2440005 ],
       [ 0.8973778 ,  0.7527344 ,  0.22886596, -0.39648576],
       [-0.16497717, -0.98080635, -0.19733729,  0.05076796]])

In [14]:
transposeme.T

array([[ 1.17018056,  0.8973778 , -0.16497717],
       [-0.23635896,  0.7527344 , -0.98080635],
       [ 0.64757156,  0.22886596, -0.19733729],
       [ 0.2440005 , -0.39648576,  0.05076796]])

In [15]:
transposeme.transpose()

array([[ 1.17018056,  0.8973778 , -0.16497717],
       [-0.23635896,  0.7527344 , -0.98080635],
       [ 0.64757156,  0.22886596, -0.19733729],
       [ 0.2440005 , -0.39648576,  0.05076796]])

In [16]:
transposeme.swapaxes(0,1)

array([[ 1.17018056,  0.8973778 , -0.16497717],
       [-0.23635896,  0.7527344 , -0.98080635],
       [ 0.64757156,  0.22886596, -0.19733729],
       [ 0.2440005 , -0.39648576,  0.05076796]])

## Envolventes (wrappers) para funciones de Python que procesan datos escalares

In [17]:
wrapme = np.random.rand(4,3)
wrapme

array([[0.4853768 , 0.54669704, 0.63091637],
       [0.99422354, 0.94167243, 0.27167836],
       [0.14174163, 0.5900368 , 0.93445929],
       [0.68619089, 0.97147088, 0.72738247]])

In [18]:
import math
math.sqrt(9.99)

3.1606961258558215

In [19]:
math.sqrt(wrapme) # Produce error de tiempo de ejecución

TypeError: only length-1 arrays can be converted to Python scalars

In [20]:
np.sqrt(wrapme)

array([[0.69668989, 0.73938964, 0.79430245],
       [0.99710759, 0.97039808, 0.52122774],
       [0.37648589, 0.76813853, 0.96667434],
       [0.8283664 , 0.98563222, 0.8528672 ]])

## Broadcasting
Es posible crear expresiones en Python donde se combinen variables de múltiples dimensiones con operadores y variables escalares

### Operaciones aritméticas con un arreglo numpy y valores escalares

In [21]:

bcast1 = np.array(range(4))
bcast1 = bcast1.reshape(-1,1)
bcast1 + 100


array([[100],
       [101],
       [102],
       [103]])

In [22]:
bcast1 - 1

array([[-1],
       [ 0],
       [ 1],
       [ 2]])

In [23]:
bcast1 * 10

array([[ 0],
       [10],
       [20],
       [30]])

In [24]:
bcast1 / 2

array([[0. ],
       [0.5],
       [1. ],
       [1.5]])

In [25]:
bcast1

array([[0],
       [1],
       [2],
       [3]])

### Operaciones con matrices de distintas dimensiones en las que se aplica broadcasting para alinear las dimensiones de las matrices y admitir la operación

In [26]:
bcast2 = np.array(range(6)).reshape(2,3)
bcast2

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
bcast100 = np.array([100,100,100]).reshape(1,3)
bcast2 + bcast100

array([[100, 101, 102],
       [103, 104, 105]])

In [28]:
bcast3 = np.array(range(9)).reshape(3,-1)
bcast3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
bcast4 = bcast100.reshape(3,-1)
bcast4

array([[100],
       [100],
       [100]])

In [30]:
bcast3 + bcast4

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108]])

### Producto dot
np.dot es el producto dot de dos matrices
https://en.wikipedia.org/wiki/Dot_product

|A B| (dot) |E F| = | A\*E+B\*G A\*F+B\*H |

|C D|  .....  |G H| = | C\*E+D\*G C\*F+D\*H |

In [31]:
mat1 = np.array(range(4)).reshape(2,-1)
mat1

array([[0, 1],
       [2, 3]])

In [32]:
mat2 = np.array([10,20,30,40]).reshape(2,-1)
mat2

array([[10, 20],
       [30, 40]])

In [33]:
np.dot(mat1,mat2)

array([[ 30,  40],
       [110, 160]])

In [34]:
#Multiplicación elemento-a-elemento de matrices
mat1*mat2

array([[  0,  20],
       [ 60, 120]])